spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: admin-route
          uri: lb://mall-admin
          predicates:
            - Path=/admin/**
          filters:
            - RewritePath=/admin/(?<segment>.*),/admin/$\{segment}
        - id: product-route
          uri: lb://mall-product
          predicates:
            - Path=/product/**
          filters:
            - RewritePath=/product/(?<segment>.*),/product/$\{segment}
  application:
    name: mall-gateway
server:
  port: 88
