datasource.url: jdbc:mysql://47.96.129.108:3306/mall-admin?serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
datasource.username: root
datasource.password: 179e15eae84c94e0

redis.host: localhost
redis.port: 6379
redis.password:

logging.config: classpath:logback-spring.xml
logging.path: D:\logs\fa

file.upload-path: http://www.cairuoyu.com/f/p4/
file.download-path: /home/cry/projects/f/p4/

token.timeout: 3600
